### ISSUE TITLE
Docker-compose?

### ISSUE THREAD

**Issue by haffi96** [binkhq/api-reflector#59]
Could a docker-compose be helpful for local testing, mainly when using it as mock service locally

Below is a working example with the current Dockerfile:

```
version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    user: postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api-reflector:
    build: .
    ports:
      - "6500:6500"
    volumes:
      - type: bind
        source: /Update/this/to/the/path/for/apireflector/repo # FIXME: Update this to your repo
        target: /app
    env_file:
      - ./.env.example
    environment:
      - postgres_dsn=postgresql://postgres:pass@postgres/postgres
    entrypoint: sh -c "gunicorn --workers=2 --threads=2 --error-logfile=- --access-logfile=- --bind=0.0.0.0:6500 wsgi --reload"
    depends_on:
      postgres:
        condition: service_healthy
```
